; Project main settings
[PROJECT]
name=esp-fly-in-peace-micro
version=0.1.0.0
description="Paragliding variometer based on ESP32-C3 platform"
cybersecurity=off

; DEPENDENCIES section
; one line per library with the format `library_name=version
;[DEPENDENCIES]
;dependency_package_1=1.2.3
;dependency_package_2=2.3.4

; HOOKS section
; This section allows you to define scripts that will be executed
; before and after tool command executions.
;[HOOKS]
;keil.build.prescript=../scripts/micro/pre_build.sh
;keil.build.postscript=../scripts/micro/post_build.sh
;ccpp.setup.prescript=../scripts/micro/pre_setup.sh

;[PUBLISH]
;output_name={name}-v{mayor}.{minor}.{patch}-build{build}
[CODE]
style=Microsoft
